package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaBool result;
        
        Control
            (final CatalaBool publicnetwork_in, final CatalaBool controls_in,
             final CatalaBool proper_in) {
            final CatalaBool publicnetwork = publicnetwork_in;
            final CatalaBool controls = controls_in;
            final CatalaBool proper = proper_in;
            final CatalaBool
                result = publicnetwork.and(controls.and(proper).not());
            this.result = result;
            NativeBridge.capture(this, "result", this.result);
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaBool result;
            ControlOut (final CatalaBool result) {
                this.result = result;
            NativeBridge.capture(this, "result", this.result);
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
        
        public static Control apply(final CatalaBool publicnetwork_in,
                                    final CatalaBool controls_in,
                                    final CatalaBool proper_in) {
            return new Control(publicnetwork_in, controls_in, proper_in);
        }
    }
    
}
