package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaBool result;
        
        Control
            (final CatalaBool newproduct_in,
             final CatalaBool seeksauthorisation_in,
             final CatalaBool existingtokenisation_in,
             final CatalaBool materialchange_in) {
            final CatalaBool newproduct = newproduct_in;
            final CatalaBool seeksauthorisation = seeksauthorisation_in;
            final CatalaBool existingtokenisation = existingtokenisation_in;
            final CatalaBool materialchange = materialchange_in;
            final CatalaBool
                result = newproduct.and(seeksauthorisation).or
                          (existingtokenisation.or(materialchange));
            this.result = result;
            NativeBridge.capture(this, "result", this.result);
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaBool result;
            ControlOut (final CatalaBool result) {
                this.result = result;
            NativeBridge.capture(this, "result", this.result);
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
        
        public static Control apply(final CatalaBool newproduct_in,
                                    final CatalaBool seeksauthorisation_in,
                                    final CatalaBool existingtokenisation_in,
                                    final CatalaBool materialchange_in) {
            return new Control(newproduct_in, seeksauthorisation_in,
                               existingtokenisation_in, materialchange_in);
        }
    }
    
}
