package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N3 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N3 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N3Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N3Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N3 (N3Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N6 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N6 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N6Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N6Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N6 (N6Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N9 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N9 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N9Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N9Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N9 (N9Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N11 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N11 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N11Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N11Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N11 (N11Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N13 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N13 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N13Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N13Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N13 (N13Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N16 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N16 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N16Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N16Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N16 (N16Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N19 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N19 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N19Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N19Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N19 (N19Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N22 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N22 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N22Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N22Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N22 (N22Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
