package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Lowered.catala_en", 29, 12, 29, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 30, 12, 30, 20,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 36, 148, 36, 157,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 36, 242, 36, 250,
                new String[]{"Generated RuleIR calculations"}));
    }

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N1 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N1 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("0");
            final CatalaInteger resultValue = new CatalaInteger("0");
            final CatalaOption<CatalaTuple> trueCount;
            final CatalaInteger trueCount__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                trueCount1 = tup_arg_58 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_58.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_58.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                trueCount1__1 = x -> {
                    if (x.code.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return new CatalaInteger("1");
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> trueCount1__2 =
                operands.map(trueCount1__1).reduce(trueCount1);
            if (trueCount1__2.isNone()) {
                trueCount__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = trueCount1__2.get();
                trueCount__1 = x__1;
            }
            trueCount = CatalaOption.some
                         (new CatalaTuple(trueCount__1, Globals.loc.get(0)));
            final CatalaOption<CatalaTuple> trueSlot;
            final CatalaInteger trueSlot__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                trueSlot1 = tup_arg_59 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_59.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_59.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                trueSlot1__1 = x__1 -> {
                    if (x__1.code.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.slot.add(new CatalaInteger("1"));
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> trueSlot1__2 =
                operands.map(trueSlot1__1).reduce(trueSlot1);
            if (trueSlot1__2.isNone()) {
                trueSlot__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = trueSlot1__2.get();
                trueSlot__1 = x__2;
            }
            trueSlot = CatalaOption.some
                        (new CatalaTuple(trueSlot__1, Globals.loc.get(1)));
            final CatalaInteger selected;
            final CatalaFunction<Operand,CatalaBool>
                selected__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            final CatalaFunction<Operand,CatalaBool>
                selected__2 = x__3 -> {
                    return x__3.code.equalsTo(new CatalaInteger("4")); };
            if (CatalaBool.of(operands.find(selected__1).isSome()).or
                 (CatalaBool.of(operands.find(selected__2).isSome())).asBoolean()) {
                selected = new CatalaInteger("-1");
            } else {
                final CatalaInteger selected__3;
                if (trueCount.isNone()) {
                    throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(2));
                } else {
                    CatalaTuple arg = trueCount.get();
                    selected__3 = CatalaValue.<CatalaInteger>cast
                       (arg.get(0));
                }
                if (selected__3.greaterThan(new CatalaInteger("1")).asBoolean()) {
                    selected = new CatalaInteger("-2");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        selected__4 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(selected__4).isSome()).asBoolean()) {
                        selected = new CatalaInteger("-1");
                    } else {
                        if (trueSlot.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(3));
                        } else {
                            CatalaTuple arg = trueSlot.get();
                            selected = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                    }
                }
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N1Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N1Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N1 (N1Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N2 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N2 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("0");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N2Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N2Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N2 (N2Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N4 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N4 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("10");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N4Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N4Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N4 (N4Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N6 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N6 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("10");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N6Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N6Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N6 (N6Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
