package hk.legalmath;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

/** Generated RuleIR 0.1 policy. Authority is supplied by an external release record. */
public final class Policy_c1a8a233f74b6d5456c4 {
    private Policy_c1a8a233f74b6d5456c4() {}
    public static final String BUNDLE_HASH = "c1a8a233f74b6d5456c4db5844c00875afdd06e316b843025f136c12368d3f09";
    private static final Policy POLICY = new Policy(new String(Base64.getDecoder().decode(String.join("", new String[]{
"eyJidW5kbGVfaWQiOiJleGNlcHRpb24udGVzdCIsImZhY3RzIjpbeyJkZXNjcmlwdGlvbiI6ImEiLCJuYW1lIjoiYSIsInR5cGUiOiJib29sIn0seyJkZXNjcmlwdGlvbiI6ImIiLCJuYW1lIjoiYiIsInR5cGUiOiJib29sIn1dLCJpbnRlcnByZXRhdGlvbnMiOlt7ImJhc2lzIjoic3ludGhldGljX3Rlc3QiLCJpZCI6Im1lYW5pbmcubWFpbiIsImlzc3VlX2lkcyI6W10sInNvdXJjZV9zcGFuX2lkcyI6WyJzcGkuYW5uZXgxLjMuMSJdLCJzdGF0ZW1lbnQiOiJTeW50aGV0aWMgbGFuZ3VhZ2UgY29uZm9ybWFuY2UgZXhhbXBsZTsgbm90IGFuIGFkZGl0aW9uYWwgU0ZDIHJ1bGUuIn1dLCJydWxlcyI6W3siYm9keSI6eyJiYXNlIjp7Im5vZGVfaWQiOiJiYXNlIiwib3AiOiJsaXRlcmFsIiwidHlwZSI6ImludGVnZXIiLCJ2YWx1ZSI6IjAifSwiZXhjZXB0aW9ucyI6W3siZXhjZXB0aW9uX2lkIjoiYSIsImd1YXJkIjp7Im5hbWUiOiJhIiwibm9kZV9pZCI6ImEuZ3VhcmQiLCJvcCI6ImZhY3QifSwiaW50ZXJwcmV0YXRpb25faWQiOiJtZWFuaW5nLm1haW4iLCJzb3VyY2Vfc3Bhbl9pZHMiOlsic3BpLmFubmV4MS4zLjEiXSwidmFsdWUiOnsibm9kZV9pZCI6ImEudmFsdWUiLCJvcCI6ImxpdGVyYWwiLCJ0eXBlIjoiaW50ZWdlciIsInZhbHVlIjoiMTAifX0seyJleGNlcHRpb25faWQiOiJiIiwiZ3VhcmQiOnsibmFtZSI6ImIiLCJub2RlX2lkIjoiYi5ndWFyZCIsIm9wIjoiZmFjdCJ9LCJpbnRlcnByZXRhdGlvbl9pZCI6Im1lYW5pbmcubWFpbiIsInNvdXJjZV9zcGFuX2lkcyI6WyJzcGkuYW5uZXgxLjMuMSJdLCJ2YWx1ZSI6eyJub2RlX2lkIjoiYi52YWx1ZSIsIm9wIjoibGl0ZXJhbCIsInR5cGUiOiJpbnRlZ2VyIiwidmFsdWUiOiIxMCJ9fV0sIm5vZGVfaWQiOiJkZWZhdWx0Iiwib3AiOiJkZWZhdWx0In0sImlkIjoiZXhjZXB0aW9uLnRlc3QiLCJpbnRlcnByZXRhdGlvbl9pZCI6Im1lYW5pbmcubWFpbiIsInNjb3BlIjp7Im5vZGVfaWQiOiJzY29wZS50cnVlIiwib3AiOiJsaXRlcmFsIiwidHlwZSI6ImJvb2wiLCJ2YWx1ZSI6dHJ1ZX0sInNvdXJjZV9zcGFuX2lkcyI6WyJzcGkuYW5uZXgxLjMuMSJdLCJ0eXBlIjoiaW50ZWdlciJ9XSwic291cmNlX3NwYW5zIjpbeyJlbmQiOjIxMDcsImlkIjoic3BpLmFubmV4MS4zLjEiLCJwYWdlIjoxLCJxdW90ZV9zaGEyNTYiOiIxMmU1NWQzNjg0ODkyN2ZhYWQ4MmM1MTliOGIzZjc1YjdhNzE2MmNjNzllZmE3YzNkMGNmZmVhYTg5YmFhZGVkIiwicmF3X3NoYTI1NiI6ImY4MzcxOTk4MWQ3NGVkMDZiYjYyY2NmMTIxYmQ3MjA0ZjgwYTExNDZhZTUwNDBmNGM0YWFiOTA1ZGY1MTBjNGEiLCJzb3VyY2VfaWQiOiIyM0VDMzUvYW5uZXgxIiwic3RhcnQiOjE4NTksInRleHRfc2hhMjU2IjoiNjc4MDYwMDYwMGU3N2QyZmJmZjVmNGExNGI0ZGIyMzdjNGMzOTQzNzY0YTg0ODQ0YWFkOGFkOWNkMzQ2ZTU4OSJ9XSwic3BlY192ZXJzaW9uIjoiMC4xIiwidmFsaWRfZnJvbSI6IjIwMjMtMDctMjhUMDA6MDA6MDAuMDAwMDAwWiIsInZhbGlkX3VudGlsIjpudWxsfQ=="
    })), StandardCharsets.UTF_8), new catala.stdlib.RuleIRBackend(), "legalmath-catala-java/0.2.0");
    public static String evaluate(String snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
    public static Map<String,Object> evaluate(Map<String,Object> snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
}
