package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Native.catala_en", 6, 10, 6, 16,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 12, 81, 12, 82,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 13, 82, 13, 83,
                new String[]{"Declared factual interface"}));
    }

    public static class Control extends CatalaStruct {
        
        final CatalaInteger result;
        
        Control (final CatalaBool first_in, final CatalaBool second_in) {
            final CatalaBool first = first_in;
            final CatalaBool second = second_in;
            final CatalaInteger result;
            if (second.asBoolean()) {
                result = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("1"),
                       Globals.loc.get(2))).get(0));
            } else if (first.asBoolean()) {
                result = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("1"),
                       Globals.loc.get(1))).get(0));
            } else {
                result = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("0"),
                       Globals.loc.get(0))).get(0));
            }
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaInteger result;
            ControlOut (final CatalaInteger result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
