package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Native.catala_en", 6, 10, 6, 16,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 12, 81, 12, 82,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 13, 82, 13, 83,
                new String[]{"Declared factual interface"}));
    }

    public static class Control extends CatalaStruct {
        
        final CatalaInteger result;
        
        Control (final CatalaBool first_in, final CatalaBool second_in) {
            final CatalaBool first = first_in;
            final CatalaBool second = second_in;
            final CatalaInteger result;
            final CatalaInteger result__1;
            final CatalaOption<CatalaTuple> result1;
            if (NativeTrace.branch("Native.catala_en", 12, 56, 12, 61, NativeTrace.condition("Native.catala_en", 12, 56, 12, 61, first)).asBoolean()) {
                result1 = CatalaOption.some
                           (new CatalaTuple
                             (new CatalaInteger("1"),
                              Globals.loc.get(1)));
            } else {
                result1 = CatalaOption.none();
            }
            final CatalaOption<CatalaTuple> result1__1;
            if (NativeTrace.branch("Native.catala_en", 13, 56, 13, 62, NativeTrace.condition("Native.catala_en", 13, 56, 13, 62, second)).asBoolean()) {
                result1__1 = CatalaOption.some
                              (new CatalaTuple
                                (new CatalaInteger("2"),
                                 Globals.loc.get(2)));
            } else {
                result1__1 = CatalaOption.none();
            }
            CatalaOption<CatalaTuple> result1__2 =
                CatalaConflict.handleExceptions
                 (new CatalaArray<>(
                  result1,
                  result1__1
                  ));
            if (NativeTrace.option("Native.catala_en", 6, 10, 6, 16, result1__2.isNone())) {
                result__1 = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("0"),
                       Globals.loc.get(0))).get(0));
            } else {
                CatalaTuple x = result1__2.get();
                result__1 = CatalaValue.<CatalaInteger>cast(x.get(0));
            }
            result = result__1;
            this.result = result;
            NativeBridge.capture(this, "result", this.result);
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaInteger result;
            ControlOut (final CatalaInteger result) {
                this.result = result;
            NativeBridge.capture(this, "result", this.result);
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
        
        public static Control apply(final CatalaBool first_in,
                                    final CatalaBool second_in) {
            return new Control(first_in, second_in);
        }
    }
    
}
