package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Native.catala_en", 6, 10, 6, 16,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 12, 81, 12, 82,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 13, 82, 13, 83,
                new String[]{"Declared factual interface"}));
    }

    public static class Control extends CatalaStruct {
        
        final CatalaInteger result;
        
        Control (final CatalaBool first_in, final CatalaBool second_in) {
            final CatalaBool first = first_in;
            final CatalaBool second = second_in;
            final CatalaInteger result;
            final CatalaOption<CatalaTuple> result__1;
            if (first.asBoolean()) {
                result__1 = CatalaOption.some
                             (new CatalaTuple
                               (new CatalaInteger("1"),
                                Globals.loc.get(1)));
            } else {
                result__1 = CatalaOption.none();
            }
            final CatalaOption<CatalaTuple> result__2;
            if (second.asBoolean()) {
                result__2 = CatalaOption.some
                             (new CatalaTuple
                               (new CatalaInteger("2"),
                                Globals.loc.get(2)));
            } else {
                result__2 = CatalaOption.none();
            }
            CatalaOption<CatalaTuple> result__3 =
                CatalaConflict.handleExceptions
                 (new CatalaArray<>(
                  result__1,
                  result__2
                  ));
            if (result__3.isNone()) {
                result = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("0"),
                       Globals.loc.get(0))).get(0));
            } else {
                CatalaTuple x = result__3.get();
                result = CatalaValue.<CatalaInteger>cast(x.get(0));
            }
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaInteger result;
            ControlOut (final CatalaInteger result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
