"""Build synthetic examples and proposed extension tasks; no regulatory authority."""
from pathlib import Path
import hashlib,json
R=Path(__file__).resolve().parents[1];out=R/'docs/monograph/contracts'
def h(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def dump(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
v='interpretation.v1';stamp='2026-09-22T00:00:00.000000Z'
policy=json.loads((out/'reference-policy.json').read_text())
source={'authority':'SYNTHETIC_METHOD_FIXTURE','text':'Fixture condition: a gift linked to a product or a product type, with a fee-discount exception. The definition is unavailable.'}
sh=h(source)
actions=[]
for i,role in enumerate(policy['required_initial_roles'],1):
 actions.append(dict(schema_version=v,action_id=f'action-{i}',run_id='run-fixture',issue_root_id=None,initial_role=role,round=0,kind='INITIAL_PROPOSAL',question=f'Produce the {role} record for the fixture.',success_criterion='Return validated structured output with evidence references.',input_hashes=[sh],adapter_id='scripted.v1',idempotency_key=f'key-{i}',state='SUCCEEDED',issued_at=stamp,timeout_seconds=30,fencing_token=1,lease_owner=None,result_ref=f'result-{i}',substantive_outcome='PROGRESS',issued_charge=1,token_reservation=None,cost_reservation_minor_units=None,remote_idempotency='NOT_APPLICABLE'))
for i,root,round_,kind,outcome in [(5,'issue-type',1,'REPAIR','PROGRESS'),(6,'issue-definition',1,'RETRIEVE','UNAVAILABLE'),(7,'issue-definition',2,'ARGUMENT','NO_PROGRESS'),(8,'issue-definition',3,'REVIEW_QUESTION','NO_PROGRESS')]:
 a=dict(actions[0]);a.update(action_id=f'action-{i}',issue_root_id=root,initial_role=None,round=round_,kind=kind,question='Investigate the recorded source question.',success_criterion='Supply the typed resolution evidence required for this issue.',idempotency_key=f'key-{i}',result_ref=f'result-{i}',substantive_outcome=outcome,state='TIMED_OUT' if i==6 else 'SUCCEEDED');actions.append(a)
candidates=[]
for ident,parent,status,statement,family,act in [('candidate-omission',None,'DEFEATED','Gift and specific product and no discount.','product-link',2),('candidate-repaired','candidate-omission','ACTIVE','Gift and (specific product or product type) and no discount.','product-or-type',5),('candidate-definition',None,'ACTIVE','Apply the same structure, but require adjudication of the discount definition.','discount-definition',4)]:
 candidates.append(dict(schema_version=v,candidate_id=ident,run_id='run-fixture',parent_id=parent,source_packet_hash=sh,source_unit_ids=['fixture.p1'],family_ids=[family],subject_unit='One synthetic benefit component',controlled_language=statement,bundle_hash=None,assumptions=[dict(assumption_id='assumption-discount',statement='The applicable fee-discount definition must be established.',provenance_refs=['fixture.p1'],status='DISPUTED')],arguments=[],issue_ids=['issue-type','issue-definition'] if ident=='candidate-omission' else ['issue-definition'],status=status,disposition_reason='Omission defeated by the fixture text.' if status=='DEFEATED' else 'Definition remains unresolved.',scheduling_priority=1,score_purpose='INVESTIGATION_PRIORITY_ONLY',probability_of_legal_correctness=None,generation_phase='SHARED_RESOLUTION' if parent else 'BLIND_INITIAL',action_id=f'action-{act}',revision_reason='Repair explicit product-type omission.' if parent else 'Initial fixture proposal.'))
issues=[]
for ident,kind,resolution,reason,evidence,attempts in [('issue-type','FORMAL_MISMATCH','RESOLVED_EVIDENCE','RESOLVED',['evidence-type-repair'],['action-5']),('issue-definition','DEFINITION','UNRESOLVED','ROUND_LIMIT',[],['action-6','action-7','action-8'])]:
 issues.append(dict(schema_version=v,issue_id=ident,root_id=ident,parent_issue_id=None,run_id='run-fixture',source_unit_ids=['fixture.p1'],candidate_ids=[x['candidate_id'] for x in candidates],kind=kind,question='Establish the source-supported condition or definition.',observed_difference='Candidates disagree or lack a required definition.',materiality='MATERIAL',processing_state='TERMINAL',resolution_state=resolution,terminal_reason=reason,resolution_evidence_refs=evidence,attempted_action_ids=attempts,evidence_needed='Inspected source or authenticated adjudication of the classification.',affected_decisions=['synthetic incentive classification'],revision=2))
coverage=dict(schema_version=v,coverage_id='coverage-fixture',run_id='run-fixture',source_packet_hash=sh,inventory_unit_ids=['fixture.p1'],dispositions=[dict(unit_id='fixture.p1',locator='Synthetic fixture paragraph 1',disposition='UNRESOLVED',reason='Structure repaired; definition remains unavailable.',target_refs=['issue-definition'])],required_dependency_ids=['definition-fee'],acquired_dependency_ids=[],identified_family_ids=['product-link','product-or-type','discount-definition'],explored_family_ids=['product-link','product-or-type','discount-definition'],inventory_review_status='SYNTHETIC_FIXTURE',review_decision_id=None)
passed=['candidate-validity','argument-register','report-integrity'];missing=[x for x in policy['mandatory_checks'] if x not in passed]
report=dict(schema_version=v,report_id='report-fixture',run_id='run-fixture',source_packet_hash=sh,profile_id='synthetic-component',run_status='BLOCKED_UNRESOLVED',selected_slice='One invented paragraph; not a legal judgment about 23EC46.',candidate_ids=[x['candidate_id'] for x in candidates],all_issue_ids=[x['issue_id'] for x in issues],material_unresolved_issue_ids=['issue-definition'],coverage_id='coverage-fixture',unexplored_family_ids=[],missing_dependency_ids=['definition-fee'],missing_initial_roles=[],incomplete_mandatory_checks=missing,processing_stop='ROUND_LIMIT',rounds_issued=3,actions_issued=8,probability_of_legal_correctness=None,release_eligible=False,next_decision='Establish the applicable fee-discount definition.',next_decision_owner_role='legal-interpretation-reviewer',evidence_limitations=['Scripted design example; no live model or independent legal evaluation.'],created_at='2026-09-22T00:05:00.000000Z')
run=dict(schema_version=v,run_id='run-fixture',predecessor_run_id=None,source_packet_hash=sh,profile_id='synthetic-component',policy_id=policy['policy_id'],policy_hash=h(policy),created_at=stamp,deadline='2026-09-22T00:10:00.000000Z',status='BLOCKED_UNRESOLVED',rounds_issued=3,actions_issued=8,no_progress_rounds=2,candidate_ids=report['candidate_ids'],issue_ids=report['all_issue_ids'],action_ids=[x['action_id'] for x in actions],completed_initial_roles=policy['required_initial_roles'],passed_mandatory_checks=passed,coverage_id=coverage['coverage_id'],report_id=report['report_id'],revision=9)
review=dict(schema_version=v,decision_id='decision-fixture',run_id=run['run_id'],reviewer_principal='synthetic-reviewer',reviewer_role='LEGAL_INTERPRETATION_REVIEWER',authority='LOCAL_SYNTHETIC',candidate_hash=h(candidates[1]),report_hash=h(report),source_packet_hash=sh,decision='REQUIRE_EVIDENCE',proposition='The fee-discount definition remains unresolved.',rationale='The fixture deliberately supplies no applicable definition.',strongest_objection_response='Neither generated reading supplies independent authority.',conditions=['No release authority is granted.'],evidence_refs=['fixture.p1'],recorded_at='2026-09-22T00:06:00.000000Z')
evidence=[]
for ident,kind,statement,act in [('fixture.p1','SOURCE_SPAN',source['text'],None),('evidence-type-repair','VALIDATED_REPAIR','The synthetic source includes the product-type route; scripted repair restores it.','action-5')]:
 evidence.append(dict(schema_version=v,evidence_id=ident,run_id='run-fixture',source_packet_hash=sh,kind=kind,content_hash=h(statement),statement=statement,source_unit_ids=['fixture.p1'],validation_status='VALIDATED',authority='SYNTHETIC_FIXTURE',validator_id='fixture-validator.v1',action_id=act,review_decision_id=None,domain_hash=None,comparison_result=None,legal_source_commitment_resolved=False))
pack=dict(authority='SYNTHETIC_METHOD_FIXTURE',source_packet=source,policy=policy,run=run,candidates=candidates,issues=issues,actions=actions,coverage=coverage,report=report,review_decisions=[review],issue_decisions=[],evidence=evidence)
dump(out/'examples/blocked-investigation.json',pack)

titles=['Contract models and policy','Source inventory and dependencies','Candidates and assumptions','Issue identity and lifecycle','Atomic budgets and outbox','Scripted controller','Comparisons and witnesses','Reports and review interface','Release integration','Restricted provider adapters','Independent reference corpus','Equal-budget evaluation','Optional argumentation and search','Bank integration and shadow operation']
deps=[[],['E01'],['E01','E02'],['E01','E03'],['E04'],['E02','E03','E04','E05'],['E03','E06'],['E06','E07'],['E08'],['E05','E06'],['E02','E08'],['E10','E11'],['E12'],['E09','E12']]
accept=[['schema-valid','schema-extra-fields','policy-inconsistent'],['unanimous-omission','dependency-unavailable'],['immutable-revision','shared-definition-invalidation'],['root-inheritance','terminal-unresolved'],['last-slot-race','crash-count','stale-fence'],['repair-explicit-omission','persistent-ambiguity','no-progress','cancel-report'],['domain-inconsistent','witness-java-replay','unsupported-fragment'],['all-issues-visible','minority-preserved','report-recovery'],['no-approval','stale-approval','open-issue-release'],['no-hidden-retries','source-prompt-injection','malformed-provider'],['blind-reference','adjudicated-disagreement','reference-freeze'],['equal-budget','clustered-uncertainty','no-all-abstain-win'],['empty-extension','family-retention','search-budget'],['enterprise-identity','host-race','source-amendment','incident-rehearsal']]
files=[['src/legalmath/interpretation/contracts.py'],['src/legalmath/interpretation/inventory.py'],['src/legalmath/interpretation/candidates.py'],['src/legalmath/interpretation/issues.py'],['src/legalmath/interpretation/actions.py'],['src/legalmath/interpretation/controller.py'],['src/legalmath/interpretation/compare.py'],['src/legalmath/interpretation/report.py','src/legalmath/web'],['src/legalmath/review','src/legalmath/java/manifest.py'],['src/legalmath/interpretation/providers'],['examples/interpretation-reference','docs/evaluation'],['scripts/evaluate_interpretation.py'],['src/legalmath/interpretation/search.py'],['docs/deployment','tests/integration']]
tasks=[dict(id=f'E{i+1:02}',title=title,status='PROPOSED_NOT_IMPLEMENTED',depends_on=deps[i],planned_paths=files[i],acceptance_ids=accept[i],evidence_directory=f'artifacts/interpretation/e{i+1:02}',human_authority_required=i in (10,13)) for i,title in enumerate(titles)]
dump(R/'docs/monograph/implementation-plan.json',dict(schema_version='interpretation-plan.v1',authority='DESIGN_ONLY',existing_runtime='RuleIR 0.1, T00-T22 retained',tasks=tasks))
print({'example_actions':len(actions),'tasks':len(tasks)})
