package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Lowered.catala_en", 39, 12, 39, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 40, 12, 40, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 224, 44, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 236, 44, 246,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 73, 12, 73, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 74, 12, 74, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 78, 224, 78, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 78, 237, 78, 247,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 87, 12, 87, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 88, 12, 88, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 93, 33, 93, 42,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 93, 45, 93, 55,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 101, 12, 101, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 102, 12, 102, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 107, 33, 107, 42,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 107, 45, 107, 55,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 115, 12, 115, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 116, 12, 116, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 121, 33, 121, 42,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 121, 45, 121, 55,
                new String[]{"Generated RuleIR calculations"}));
    }

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N2 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N2 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N2Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N2Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N2 (N2Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N4 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N4 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_231 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_231.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_231.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(0)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_232 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_232.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_232.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(1)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(2));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(3));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N4Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N4Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N4 (N4Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N6 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N6 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("0");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N6Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N6Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N6 (N6Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N7 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N7 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N7Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N7Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N7 (N7Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N8 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N8 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_233 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_233.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_233.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(4)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_234 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_234.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_234.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(5)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(6));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(7));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N8Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N8Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N8 (N8Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N9 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N9 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        resultStatus = new CatalaInteger("3");
                    }
                }
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_235 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_235.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_235.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = leftValue1__2.get();
                leftValue__1 = x__2;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(8)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_236 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_236.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_236.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__2 -> {
                    if (x__2.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__2.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__3 = rightValue1__2.get();
                rightValue__1 = x__3;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(9)));
            final CatalaInteger resultValue;
            final CatalaInteger resultValue__1;
            if (leftValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(10));
            } else {
                CatalaTuple arg = leftValue.get();
                resultValue__1 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            final CatalaInteger resultValue__2;
            if (rightValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(11));
            } else {
                CatalaTuple arg = rightValue.get();
                resultValue__2 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            resultValue = resultValue__1.add(resultValue__2);
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N9Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N9Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N9 (N9Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N10 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N10 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        resultStatus = new CatalaInteger("3");
                    }
                }
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_237 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_237.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_237.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = leftValue1__2.get();
                leftValue__1 = x__2;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(12)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_238 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_238.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_238.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__2 -> {
                    if (x__2.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__2.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__3 = rightValue1__2.get();
                rightValue__1 = x__3;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple
                            (rightValue__1,
                             Globals.loc.get(13)));
            final CatalaInteger resultValue;
            final CatalaInteger resultValue__1;
            if (leftValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(14));
            } else {
                CatalaTuple arg = leftValue.get();
                resultValue__1 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            final CatalaInteger resultValue__2;
            if (rightValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(15));
            } else {
                CatalaTuple arg = rightValue.get();
                resultValue__2 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            resultValue = resultValue__1.add(resultValue__2);
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N10Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N10Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N10 (N10Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N11 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N11 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        resultStatus = new CatalaInteger("3");
                    }
                }
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_239 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_239.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_239.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = leftValue1__2.get();
                leftValue__1 = x__2;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(16)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_240 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_240.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_240.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__2 -> {
                    if (x__2.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__2.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__3 = rightValue1__2.get();
                rightValue__1 = x__3;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple
                            (rightValue__1,
                             Globals.loc.get(17)));
            final CatalaInteger resultValue;
            final CatalaInteger resultValue__1;
            if (leftValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(18));
            } else {
                CatalaTuple arg = leftValue.get();
                resultValue__1 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            final CatalaInteger resultValue__2;
            if (rightValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(19));
            } else {
                CatalaTuple arg = rightValue.get();
                resultValue__2 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            resultValue = resultValue__1.add(resultValue__2);
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N11Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N11Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N11 (N11Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
