package hk.legalmath;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

/** Generated RuleIR 0.1 policy. Authority is supplied by an external release record. */
public final class Policy_d5f9b68bbb328a7bafe7 {
    private Policy_d5f9b68bbb328a7bafe7() {}
    public static final String BUNDLE_HASH = "d5f9b68bbb328a7bafe722d9ac4c7b626c3b98b66b42275021f2b5d77c09619b";
    private static final Policy POLICY = new Policy(new String(Base64.getDecoder().decode(String.join("", new String[]{
"eyJidW5kbGVfaWQiOiJzZWFyY2guNzkyYWRhZGMyMDE5ZTc4MGRjNDkiLCJmYWN0cyI6W3siZGVzY3JpcHRpb24iOiJBIGRpc3RyaWJ1dG9yIG9mZmVycyBhIGdpZnQ7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJnaWZ0IiwidHlwZSI6ImJvb2wifSx7ImRlc2NyaXB0aW9uIjoiVGhlIGdpZnQgaXMgYSBkaXNjb3VudCBvZiBmZWVzIG9yIGNoYXJnZXM7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJkaXNjb3VudCIsInR5cGUiOiJib29sIn1dLCJpbnRlcnByZXRhdGlvbnMiOlt7ImJhc2lzIjoic3ludGhldGljX3Rlc3QiLCJpZCI6InJlYWRpbmciLCJpc3N1ZV9pZHMiOltdLCJzb3VyY2Vfc3Bhbl9pZHMiOlsicy5kOGQ0MDVhMDc5NzczLnUwLjAiXSwic3RhdGVtZW50IjoiVW5yZXZpZXdlZCBpbnRlcnByZXRhdGlvbjogW1RSVUVfSVNfUFJPSElCSVRFRF0gUmVzdWx0IHRydWUgbWVhbnMgcHJvaGliaXRlZCBnaWZ0IG9mZmVyLCB3aXRoIHRoZSBmZWUgZXhjZXB0aW9uLiJ9XSwicnVsZXMiOlt7ImJvZHkiOnsiYXJncyI6W3sibmFtZSI6ImdpZnQiLCJub2RlX2lkIjoiYm9keS4yIiwib3AiOiJmYWN0In0seyJhcmciOnsibmFtZSI6ImRpc2NvdW50Iiwibm9kZV9pZCI6ImJvZHkuNCIsIm9wIjoiZmFjdCJ9LCJub2RlX2lkIjoiYm9keS4zIiwib3AiOiJub3QifV0sIm5vZGVfaWQiOiJib2R5LjEiLCJvcCI6ImFsbCJ9LCJpZCI6InNlbGVjdGVkLmNvbnRyb2wiLCJpbnRlcnByZXRhdGlvbl9pZCI6InJlYWRpbmciLCJzY29wZSI6eyJub2RlX2lkIjoic2NvcGUuMSIsIm9wIjoibGl0ZXJhbCIsInR5cGUiOiJib29sIiwidmFsdWUiOnRydWV9LCJzb3VyY2Vfc3Bhbl9pZHMiOlsicy5kOGQ0MDVhMDc5NzczLnUwLjAiXSwidHlwZSI6ImJvb2wifV0sInNvdXJjZV9zcGFucyI6W3siZW5kIjo3OCwiaWQiOiJzLmQ4ZDQwNWEwNzk3NzMudTAuMCIsInBhZ2UiOjEsInF1b3RlX3NoYTI1NiI6ImI3OGE2NjAwZDNkMTE2YzNiNDUwMDJiOGIyYTIxN2YxYzUwNzY5NTU3NzEzZjFiNWExZTI3YWFiOTY1OTdjNzYiLCJyYXdfc2hhMjU2IjoiYjc4YTY2MDBkM2QxMTZjM2I0NTAwMmI4YjJhMjE3ZjFjNTA3Njk1NTc3MTNmMWI1YTFlMjdhYWI5NjU5N2M3NiIsInNvdXJjZV9pZCI6ImQ4ZDQwNWEwNzk3NzMiLCJzdGFydCI6MCwidGV4dF9zaGEyNTYiOiJiNzhhNjYwMGQzZDExNmMzYjQ1MDAyYjhiMmEyMTdmMWM1MDc2OTU1NzcxM2YxYjVhMWUyN2FhYjk2NTk3Yzc2In1dLCJzcGVjX3ZlcnNpb24iOiIwLjEiLCJ2YWxpZF9mcm9tIjoiMjAyNi0wOS0yM1QwMDowMDowMC4wMDAwMDBaIiwidmFsaWRfdW50aWwiOm51bGx9"
    })), StandardCharsets.UTF_8));
    public static String evaluate(String snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
    public static Map<String,Object> evaluate(Map<String,Object> snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
}
