package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaBool result;
        
        Control (final CatalaBool a_in, final CatalaBool b_in) {
            final CatalaBool a = a_in;
            final CatalaBool b = b_in;
            final CatalaBool result = a.and(b);
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaBool result;
            ControlOut (final CatalaBool result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
