package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    @SuppressWarnings("unchecked")
    public static class Choice extends CatalaEnum {
        
        public enum Kind { Fixed, Empty }
        
        private final CatalaValue<?> contents;
        public final Kind kind;
        
        private Choice(Kind k, CatalaValue<?> contents) {
            this.kind = k;
            this.contents = contents;
            NativeBridge.capture(this, "contents", this.contents);
        }

        public static Choice makeFixed(CatalaDecimal v) {
            return new Choice(Kind.Fixed, v);
        }
        public static Choice makeEmpty() {
            return new Choice(Kind.Empty, CatalaUnit.INSTANCE);
        }
        
        public <T> T getContentsAs(Kind k, Class<T> clazz) {
            if (this.kind != k) {
              throw new IllegalArgumentException("Invalid enum contents access: expected " + k + ", got " + this.kind);
            }
            return (T) this.contents;
        }

        public CatalaDecimal getFixedContents() {
            return this.getContentsAs(Kind.Fixed, CatalaDecimal.class);
        }
    }

    public static class Selection extends CatalaStruct {
        
        final CatalaDecimal amount;
        final Choice echo;
        final CatalaOption<CatalaDecimal> optionalEcho;
        
        Selection
            (final Choice choice_in,
             final CatalaOption<CatalaDecimal> rate_in) {
            final Choice choice = choice_in;
            final CatalaOption<CatalaDecimal> rate = rate_in;
            final CatalaDecimal amount;
            final CatalaDecimal base;
            switch (choice.kind) {
                case Fixed: {
                    NativeTrace.caseTaken("Native.catala_en", 19, 21, 21, 20, "Fixed");
                    CatalaDecimal amount1 = choice.getFixedContents();
                    base = amount1;
                    break;
                }
                case Empty: {
                    NativeTrace.caseTaken("Native.catala_en", 19, 21, 21, 20, "Empty");
                    base = CatalaDecimal.of(new CatalaInteger("0"));
                    break;
                }
                default: {
                    throw new RuntimeException("Unreachable case");
                }
            }
            final CatalaDecimal amount__1;
            if (NativeTrace.option("Native.catala_en", 23, 5, 25, 22, rate.isNone())) {
                amount__1 = base;
            } else {
                CatalaDecimal amount1 = rate.get();
                amount__1 = Decimal_en.Globals.max.apply
                             (new CatalaTuple(base, amount1));
            }
            amount = amount__1;
            final Choice echo = choice;
            final CatalaOption<CatalaDecimal> optionalEcho = rate;
            this.amount = amount;
            NativeBridge.capture(this, "amount", this.amount);
            this.echo = echo;
            NativeBridge.capture(this, "echo", this.echo);
            this.optionalEcho = optionalEcho;
            NativeBridge.capture(this, "optionalEcho", this.optionalEcho);
        }
        
        static class SelectionOut extends CatalaStruct {
            final CatalaDecimal amount; final Choice echo;
            final CatalaOption<CatalaDecimal> optionalEcho;
            SelectionOut (final CatalaDecimal amount, final Choice echo,
                          final CatalaOption<CatalaDecimal> optionalEcho) {
                this.amount = amount;
            NativeBridge.capture(this, "amount", this.amount);
                this.echo = echo;
            NativeBridge.capture(this, "echo", this.echo);
                this.optionalEcho = optionalEcho;
            NativeBridge.capture(this, "optionalEcho", this.optionalEcho);
            }
        }
        
        Selection (SelectionOut result) {
            this.amount = result.amount;
            this.echo = result.echo;
            this.optionalEcho = result.optionalEcho;
        }
        
        public static Selection apply(final Choice choice_in,
                                      final CatalaOption<CatalaDecimal> rate_in) {
            return new Selection(choice_in, rate_in);
        }
    }
    
}
