package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Lowered.catala_en", 39, 12, 39, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 40, 12, 40, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 224, 44, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 237, 44, 247,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 63, 12, 63, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 64, 12, 64, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 68, 224, 68, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 68, 237, 68, 247,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 107, 12, 107, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 108, 12, 108, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 112, 224, 112, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 112, 237, 112, 247,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 161, 12, 161, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 162, 12, 162, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 166, 224, 166, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 166, 237, 166, 247,
                new String[]{"Generated RuleIR calculations"}));
    }

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N1 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N1 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N1Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N1Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N1 (N1Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N2 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N2 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_366 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_366.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_366.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(0)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_367 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_367.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_367.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(1)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(2));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(3));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N2Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N2Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N2 (N2Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N4 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N4 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger
                resultValue = new CatalaInteger("4000000000");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N4Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N4Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N4 (N4Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N5 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N5 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_368 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_368.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_368.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(4)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_369 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_369.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_369.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(5)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(6));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(7));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N5Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N5Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N5 (N5Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N7 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N7 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger
                resultValue = new CatalaInteger("8000000000");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N7Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N7Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N7 (N7Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N8 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N8 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N8Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N8Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N8 (N8Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N9 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N9 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N9Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N9Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N9 (N9Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N13 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N13 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_370 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_370.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_370.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(8)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_371 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_371.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_371.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(9)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(10));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(11));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N13Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N13Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N13 (N13Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N15 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N15 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("5");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N15Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N15Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N15 (N15Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N16 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N16 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N16Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N16Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N16 (N16Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N17 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N17 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N17Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N17Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N17 (N17Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N24 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N24 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N24Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N24Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N24 (N24Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N25 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N25 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_372 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_372.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_372.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(12)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_373 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_373.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_373.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple
                            (rightValue__1,
                             Globals.loc.get(13)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(14));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(15));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N25Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N25Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N25 (N25Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N28 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N28 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N28Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N28Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N28 (N28Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N29 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N29 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N29Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N29Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N29 (N29Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N30 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N30 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N30Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N30Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N30 (N30Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N33 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N33 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N33Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N33Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N33 (N33Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N34 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N34 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N34Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N34Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N34 (N34Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N36 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N36 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N36Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N36Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N36 (N36Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N37 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N37 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N37Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N37Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N37 (N37Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N40 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N40 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N40Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N40Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N40 (N40Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N41 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N41 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N41Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N41Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N41 (N41Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N45 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N45 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N45Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N45Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N45 (N45Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N47 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N47 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N47Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N47Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N47 (N47Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N48 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N48 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N48Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N48Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N48 (N48Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N56 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N56 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N56Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N56Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N56 (N56Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N60 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N60 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N60Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N60Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N60 (N60Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
