package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Native.catala_en", 7, 10, 7, 13,
                new String[]{"Declared factual interface"}));
    }

    public static class Deadline extends CatalaStruct {
        
        final CatalaDate due;
        final CatalaBool late;
        
        Deadline
            (final CatalaDate start_in, final CatalaInteger months_in,
             final CatalaDate assessed_in) {
            final CatalaDate start = start_in;
            final CatalaInteger months = months_in;
            final CatalaDate assessed = assessed_in;
            final CatalaDate
                due = start.addDurationRoundDown
                       (Globals.loc.get(0),
                        (CatalaDuration.of(0,1,0)).multiply(months));
            final CatalaBool late = assessed.greaterThan(due);
            this.due = due;
            NativeBridge.capture(this, "due", this.due);
            this.late = late;
            NativeBridge.capture(this, "late", this.late);
        }
        
        static class DeadlineOut extends CatalaStruct {
            final CatalaDate due;
            final CatalaBool late;
            DeadlineOut (final CatalaDate due, final CatalaBool late) {
                this.due = due;
            NativeBridge.capture(this, "due", this.due);
                this.late = late;
            NativeBridge.capture(this, "late", this.late);
            }
        }
        
        Deadline (DeadlineOut result) {
            this.due = result.due;
            this.late = result.late;
        }
        
        public static Deadline apply(final CatalaDate start_in,
                                     final CatalaInteger months_in,
                                     final CatalaDate assessed_in) {
            return new Deadline(start_in, months_in, assessed_in);
        }
    }
    
}
