package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaInteger result;
        
        Control (final CatalaInteger a_in, final CatalaInteger b_in) {
            final CatalaInteger a = a_in;
            final CatalaInteger b = b_in;
            final CatalaInteger result = a.add(b);
            this.result = result;
            NativeBridge.capture(this, "result", this.result);
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaInteger result;
            ControlOut (final CatalaInteger result) {
                this.result = result;
            NativeBridge.capture(this, "result", this.result);
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
        
        public static Control apply(final CatalaInteger a_in,
                                    final CatalaInteger b_in) {
            return new Control(a_in, b_in);
        }
    }
    
}
