package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Pilots {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                50, 10, 50, 16,
                new String[]{"An ambiguity test for defaults and exceptions"}),
              new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                58, 22, 58, 24,
                new String[]{"An ambiguity test for defaults and exceptions"}),
              new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                62, 22, 62, 24,
                new String[]{"An ambiguity test for defaults and exceptions"}));
    }

    public static class Financial extends CatalaStruct {
        
        final CatalaInteger decision;
        
        Financial
            (final CatalaBool portfolio_known_in,
             final CatalaInteger portfolio_cents_in,
             final CatalaBool assets_known_in,
             final CatalaInteger assets_cents_in) {
            final CatalaBool portfolioKnown = portfolio_known_in;
            final CatalaInteger portfolioCents = portfolio_cents_in;
            final CatalaBool assetsKnown = assets_known_in;
            final CatalaInteger assetsCents = assets_cents_in;
            final CatalaInteger decision;
            if (portfolioKnown.and
                 (portfolioCents.greaterEqThan
                   (new CatalaInteger("4000000000"))).or
                 (assetsKnown.and
                   (assetsCents.greaterEqThan(new CatalaInteger("8000000000")))).asBoolean()) {
                decision = new CatalaInteger("1");
            } else if (portfolioKnown.and(assetsKnown).asBoolean()) {
                decision = new CatalaInteger("0");
            } else {
                decision = new CatalaInteger("-1");
            }
            this.decision = decision;
        }
        
        static class FinancialOut extends CatalaStruct {
            final CatalaInteger decision;
            FinancialOut (final CatalaInteger decision) {
                this.decision = decision;
            }
        }
        
        Financial (FinancialOut result) {
            this.decision = result.decision;
        }
    }

    public static class Exceptions extends CatalaStruct {
        
        final CatalaInteger decision;
        final CatalaInteger amount;
        
        Exceptions
            (final CatalaBool first_known_in,
             final CatalaBool first_applies_in,
             final CatalaBool second_known_in,
             final CatalaBool second_applies_in) {
            final CatalaBool firstKnown = first_known_in;
            final CatalaBool firstApplies = first_applies_in;
            final CatalaBool secondKnown = second_known_in;
            final CatalaBool secondApplies = second_applies_in;
            final CatalaInteger decision;
            if (firstKnown.and
                 (firstApplies.and(secondKnown.and(secondApplies))).asBoolean()) {
                decision = new CatalaInteger("2");
            } else if (firstKnown.and(secondKnown).asBoolean()) {
                decision = new CatalaInteger("3");
            } else {
                decision = new CatalaInteger("-1");
            }
            final CatalaInteger amount;
            if (secondKnown.and(secondApplies).asBoolean()) {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("10"),
                       Globals.loc.get(2))).get(0));
            } else if (firstKnown.and(firstApplies).asBoolean()) {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("10"),
                       Globals.loc.get(1))).get(0));
            } else {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("0"),
                       Globals.loc.get(0))).get(0));
            }
            this.decision = decision;
            this.amount = amount;
        }
        
        static class ExceptionsOut extends CatalaStruct {
            final CatalaInteger decision;
            final CatalaInteger amount;
            ExceptionsOut (final CatalaInteger decision,
                           final CatalaInteger amount) {
                this.decision = decision;
                this.amount = amount;
            }
        }
        
        Exceptions (ExceptionsOut result) {
            this.decision = result.decision;
            this.amount = result.amount;
        }
    }
    
}
