package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaMoney result;
        
        Control
            (final CatalaMoney assets_in, final CatalaMoney liabilities_in,
             final CatalaMoney residence_in) {
            final CatalaMoney assets = assets_in;
            final CatalaMoney liabilities = liabilities_in;
            final CatalaMoney residence = residence_in;
            final CatalaMoney
                result = assets.subtract(liabilities).subtract(residence);
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaMoney result;
            ControlOut (final CatalaMoney result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
