package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Lowered.catala_en", 27, 10, 27, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 29, 12, 29, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 30, 12, 30, 20,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 33, 41, 33, 62,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 33, 43, 33, 52,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 34, 224, 34, 232,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 34, 239, 34, 248,
                new String[]{"Generated RuleIR calculations"}));
    }

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("1");
            final CatalaInteger resultValue = new CatalaInteger("1");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N1 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N1 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_45 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_45.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_45.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(1)));
            final CatalaOption<CatalaTuple> quotient;
            final CatalaInteger quotient__1;
            if (leftValue.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(4));
            } else {
                CatalaTuple arg = leftValue.get();
                quotient__1 = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            quotient = CatalaOption.some
                        (new CatalaTuple
                          (quotient__1.multiply(new CatalaInteger("1")).divide
                            (Globals.loc.get(3),
                             new CatalaInteger("2")).asInteger(),
                           Globals.loc.get(2)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__1 -> {
                    return x__1.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__2 -> {
                        return x__2.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__3 -> {
                            return x__3.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (quotient.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(5));
                        } else {
                            CatalaTuple arg = quotient.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(6));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.multiply(new CatalaInteger("2")).equalsTo
                             (resultStatus__5.multiply(new CatalaInteger("1"))).asBoolean()) {
                            resultStatus = new CatalaInteger("3");
                        } else {
                            resultStatus = new CatalaInteger("5");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (quotient.isNone()) {
                throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(0));
            } else {
                CatalaTuple arg = quotient.get();
                resultValue = CatalaValue.<CatalaInteger>cast(arg.get(0));
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N1Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N1Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N1 (N1Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N2 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N2 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("101");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N2Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N2Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N2 (N2Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
