package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class NetAssets extends CatalaStruct {
        
        final CatalaMoney netAssets;
        final CatalaMoney netAssetsExHome;
        
        NetAssets
            (final CatalaMoney assets_in, final CatalaMoney liabilities_in,
             final CatalaMoney residence_in) {
            final CatalaMoney assets = assets_in;
            final CatalaMoney liabilities = liabilities_in;
            final CatalaMoney residence = residence_in;
            final CatalaMoney netAssets = assets.subtract(liabilities);
            final CatalaMoney
                netAssetsExHome = netAssets.subtract(residence);
            this.netAssets = netAssets;
            this.netAssetsExHome = netAssetsExHome;
        }
        
        static class NetAssetsOut extends CatalaStruct {
            final CatalaMoney netAssets;
            final CatalaMoney netAssetsExHome;
            NetAssetsOut (final CatalaMoney netAssets,
                          final CatalaMoney netAssetsExHome) {
                this.netAssets = netAssets;
                this.netAssetsExHome = netAssetsExHome;
            }
        }
        
        NetAssets (NetAssetsOut result) {
            this.netAssets = result.netAssets;
            this.netAssetsExHome = result.netAssetsExHome;
        }
    }
    
}
