package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Holding extends CatalaStruct {
        
        public final CatalaDecimal amount;
        public final CatalaBool eligible;
        
        public Holding (final CatalaDecimal amount, final CatalaBool eligible) {
            this.amount = amount;
            NativeBridge.capture(this, "amount", this.amount);
            this.eligible = eligible;
            NativeBridge.capture(this, "eligible", this.eligible);
        }
    }

    public static class Portfolio extends CatalaStruct {
        
        final CatalaDecimal exposure;
        
        Portfolio (final CatalaArray<Holding> holdings_in) {
            final CatalaArray<Holding> holdings = holdings_in;
            final CatalaDecimal exposure;
            final CatalaFunction<CatalaTuple,CatalaDecimal>
                exposure__1 = tup_arg_12 -> {
                    CatalaDecimal sum1 = CatalaValue.<CatalaDecimal>cast
                       (tup_arg_12.get(0));
                    CatalaDecimal sum2 = CatalaValue.<CatalaDecimal>cast
                       (tup_arg_12.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Holding,CatalaDecimal>
                exposure__2 = holding -> {
                    if (holding.eligible.asBoolean()) {
                        return holding.amount;
                    } else {
                        return CatalaDecimal.of(new CatalaInteger("0"));
                    } };
            CatalaOption<CatalaDecimal> exposure__3 =
                holdings.map(exposure__2).reduce(exposure__1);
            if (exposure__3.isNone()) {
                exposure = CatalaDecimal.of(new CatalaInteger("0"));
            } else {
                CatalaDecimal x = exposure__3.get();
                exposure = x;
            }
            this.exposure = exposure;
            NativeBridge.capture(this, "exposure", this.exposure);
        }
        
        static class PortfolioOut extends CatalaStruct {
            final CatalaDecimal exposure;
            PortfolioOut (final CatalaDecimal exposure) {
                this.exposure = exposure;
            NativeBridge.capture(this, "exposure", this.exposure);
            }
        }
        
        Portfolio (PortfolioOut result) {
            this.exposure = result.exposure;
        }
    }
    
}
