package hk.legalmath;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

/** Generated RuleIR 0.1 policy. Authority is supplied by an external release record. */
public final class Policy_e76506f8ea78ff7ecfc5 {
    private Policy_e76506f8ea78ff7ecfc5() {}
    public static final String BUNDLE_HASH = "e76506f8ea78ff7ecfc5d08dabe9edb8302bf8f087d4adb3dc2d833f12fcda5b";
    private static final Policy POLICY = new Policy(new String(Base64.getDecoder().decode(String.join("", new String[]{
"eyJidW5kbGVfaWQiOiJzZWFyY2guYjcwOGJmM2FmN2NkNzliYzcyZTEiLCJmYWN0cyI6W3siZGVzY3JpcHRpb24iOiJTZXJ2aWNlcyBjb25zdGl0dXRlIHJlZ3VsYXRlZCBhY3Rpdml0eSBhZnRlciBhcHBsaWNhYmxlIGNhcnZlLW91dHM7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJyZWd1bGF0ZWQiLCJ0eXBlIjoiYm9vbCJ9LHsiZGVzY3JpcHRpb24iOiJQcm92aXNpb24gb2YgdGhlIHNlcnZpY2VzIGNvbnN0aXR1dGVzIGNhcnJ5aW5nIG9uIGEgYnVzaW5lc3M7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJidXNpbmVzcyIsInR5cGUiOiJib29sIn0seyJkZXNjcmlwdGlvbiI6IlRoYXQgYnVzaW5lc3MgaXMgY2FycmllZCBvbiBpbiBIb25nIEtvbmc7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJob25nX2tvbmciLCJ0eXBlIjoiYm9vbCJ9XSwiaW50ZXJwcmV0YXRpb25zIjpbeyJiYXNpcyI6InJldmlld2VyX2ludGVycHJldGF0aW9uIiwiaWQiOiJyZWFkaW5nIiwiaXNzdWVfaWRzIjpbXSwic291cmNlX3NwYW5faWRzIjpbInMuZGFhMTg3NjMxNjY0MS51MzguMjc2ODEiXSwic3RhdGVtZW50IjoiVW5yZXZpZXdlZCBpbnRlcnByZXRhdGlvbjogW1RSVUVfSVNfQ09NUExJQU5UXSBUcnVlIG1lYW5zIHRoZSBzZWxlY3RlZCBhcHBsaWNhYmlsaXR5IHRyaWdnZXIgaXMgc2F0aXNmaWVkLCBub3QgZ2VuZXJhbCBjb21wbGlhbmNlLiJ9XSwicnVsZXMiOlt7ImJvZHkiOnsiYXJncyI6W3sibmFtZSI6InJlZ3VsYXRlZCIsIm5vZGVfaWQiOiJib2R5LjIiLCJvcCI6ImZhY3QifSx7Im5hbWUiOiJob25nX2tvbmciLCJub2RlX2lkIjoiYm9keS4zIiwib3AiOiJmYWN0In1dLCJub2RlX2lkIjoiYm9keS4xIiwib3AiOiJhbGwifSwiaWQiOiJzZWxlY3RlZC5jb250cm9sIiwiaW50ZXJwcmV0YXRpb25faWQiOiJyZWFkaW5nIiwic2NvcGUiOnsibm9kZV9pZCI6InNjb3BlLjEiLCJvcCI6ImxpdGVyYWwiLCJ0eXBlIjoiYm9vbCIsInZhbHVlIjp0cnVlfSwic291cmNlX3NwYW5faWRzIjpbInMuZGFhMTg3NjMxNjY0MS51MzguMjc2ODEiXSwidHlwZSI6ImJvb2wifV0sInNvdXJjZV9zcGFucyI6W3siZW5kIjoyODE2NywiaWQiOiJzLmRhYTE4NzYzMTY2NDEudTM4LjI3NjgxIiwicGFnZSI6MSwicXVvdGVfc2hhMjU2IjoiNjA0NTc3ZDViY2NiOTlkNmEzNjYxNjk3NTBhNDhiMmZhODljNmRhMTQzYjliZTUzNzk2OWNlZjY2Mzc4ODNlMCIsInJhd19zaGEyNTYiOiJmNmVkMmQ1MzVhNTA5Y2Q0ZWY3NjI5ZmQxYzUzMTU5ZGNjZDllMTgyODJhYTAzY2Q4NjJlZDA3MGI4NDQwZjJjIiwic291cmNlX2lkIjoiZGFhMTg3NjMxNjY0MSIsInN0YXJ0IjoyNzY4MSwidGV4dF9zaGEyNTYiOiJjZDc0NmNmODQ4ZjcwMzZiNmIyMTYxNWI3YmFlNTMwMGQ4ZTcwNDZkYTVlYTIxZDM1OTAwNzU2MDQ1MDEyOGY3In1dLCJzcGVjX3ZlcnNpb24iOiIwLjEiLCJ2YWxpZF9mcm9tIjoiMjAyNi0wOS0yNFQwNDoyMDowMC4wMDAwMDBaIiwidmFsaWRfdW50aWwiOm51bGx9"
    })), StandardCharsets.UTF_8));
    public static String evaluate(String snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
    public static Map<String,Object> evaluate(Map<String,Object> snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
}
