package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    @SuppressWarnings("unchecked")
    public static class Category extends CatalaEnum {
        
        public enum Kind { Ordinary, Preferred, Excluded }
        
        private final CatalaValue<?> contents;
        public final Kind kind;
        
        private Category(Kind k, CatalaValue<?> contents) {
            this.kind = k;
            this.contents = contents;
        }

        public static Category makeOrdinary() {
            return new Category(Kind.Ordinary, CatalaUnit.INSTANCE);
        }
        public static Category makePreferred() {
            return new Category(Kind.Preferred, CatalaUnit.INSTANCE);
        }
        public static Category makeExcluded() {
            return new Category(Kind.Excluded, CatalaUnit.INSTANCE);
        }
        
        public <T> T getContentsAs(Kind k, Class<T> clazz) {
            if (this.kind != k) {
              throw new IllegalArgumentException("Invalid enum contents access: expected " + k + ", got " + this.kind);
            }
            return (T) this.contents;
        }
    }

    public static class Classification extends CatalaStruct {
        
        final CatalaInteger amount;
        
        Classification
            (final Category category_in, final CatalaInteger base_in) {
            final Category category = category_in;
            final CatalaInteger base = base_in;
            final CatalaInteger amount;
            switch (category.kind) {
                case Ordinary: {
                    amount = base;
                    break;
                }
                case Preferred: {
                    amount = (new CatalaInteger("2")).multiply(base);
                    break;
                }
                case Excluded: {
                    amount = new CatalaInteger("0");
                    break;
                }
                default: {
                    throw new RuntimeException("Unreachable case");
                }
            }
            this.amount = amount;
        }
        
        static class ClassificationOut extends CatalaStruct {
            final CatalaInteger amount;
            ClassificationOut (final CatalaInteger amount) {
                this.amount = amount;
            }
        }
        
        Classification (ClassificationOut result) {
            this.amount = result.amount;
        }
    }
    
}
