package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Person extends CatalaStruct {
        
        public final CatalaInteger age;
        public final CatalaInteger rate;
        
        public Person (final CatalaInteger age, final CatalaInteger rate) {
            this.age = age;
            this.rate = rate;
        }
    }

    public static class Entitlement extends CatalaStruct {
        
        final CatalaInteger amount;
        
        Entitlement (final CatalaInteger age_in, final CatalaInteger rate_in)
        {
            final CatalaInteger age = age_in;
            final CatalaInteger rate = rate_in;
            final CatalaInteger amount;
            if (age.greaterEqThan(new CatalaInteger("18")).asBoolean()) {
                amount = rate;
            } else {
                amount = new CatalaInteger("0");
            }
            this.amount = amount;
        }
        
        static class EntitlementOut extends CatalaStruct {
            final CatalaInteger amount;
            EntitlementOut (final CatalaInteger amount) {
                this.amount = amount;
            }
        }
        
        Entitlement (EntitlementOut result) {
            this.amount = result.amount;
        }
    }

    public static class Household extends CatalaStruct {
        
        final CatalaInteger total;
        
        Household (final CatalaArray<Person> people_in) {
            final CatalaArray<Person> people = people_in;
            final CatalaInteger total;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                total__1 = tup_arg_17 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_17.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_17.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Person,CatalaInteger>
                total__2 = person -> {
                    final Entitlement
                        result = new Entitlement(person.age, person.rate);
                    return (new Entitlement(new Entitlement.EntitlementOut(result.amount))).amount; };
            CatalaOption<CatalaInteger> total__3 =
                people.map(total__2).reduce(total__1);
            if (total__3.isNone()) {
                total = new CatalaInteger("0");
            } else {
                CatalaInteger x = total__3.get();
                total = x;
            }
            this.total = total;
        }
        
        static class HouseholdOut extends CatalaStruct {
            final CatalaInteger total;
            HouseholdOut (final CatalaInteger total) {
                this.total = total;
            }
        }
        
        Household (HouseholdOut result) {
            this.total = result.total;
        }
    }
    
}
