package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Native.catala_en", 6, 10, 6, 17,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 15, 66, 15, 70,
                new String[]{"Declared factual interface"}),
              new CatalaPosition
               ("Native.catala_en", 17, 67, 17, 72,
                new String[]{"Declared factual interface"}));
    }

    public static class Permission extends CatalaStruct {
        
        final CatalaBool allowed;
        
        Permission
            (final CatalaBool licensed_in, final CatalaBool suspended_in) {
            final CatalaBool licensed = licensed_in;
            final CatalaBool suspended = suspended_in;
            final CatalaBool allowed;
            if (suspended.asBoolean()) {
                allowed = CatalaValue.<CatalaBool>cast
                   ((new CatalaTuple(CatalaBool.FALSE, Globals.loc.get(2))).get(0));
            } else if (licensed.asBoolean()) {
                allowed = CatalaValue.<CatalaBool>cast
                   ((new CatalaTuple(CatalaBool.TRUE, Globals.loc.get(1))).get(0));
            } else {
                allowed = CatalaValue.<CatalaBool>cast
                   ((new CatalaTuple(CatalaBool.FALSE, Globals.loc.get(0))).get(0));
            }
            this.allowed = allowed;
        }
        
        static class PermissionOut extends CatalaStruct {
            final CatalaBool allowed;
            PermissionOut (final CatalaBool allowed) {
                this.allowed = allowed;
            }
        }
        
        Permission (PermissionOut result) {
            this.allowed = result.allowed;
        }
    }
    
}
