package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Pilots {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                50, 10, 50, 16,
                new String[]{"An ambiguity test for defaults and exceptions"}),
              new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                58, 22, 58, 24,
                new String[]{"An ambiguity test for defaults and exceptions"}),
              new CatalaPosition
               ("/home/chakwong/python/legalmath/.worktrees/catala/examples/catala/Pilots.catala_en",
                62, 22, 62, 24,
                new String[]{"An ambiguity test for defaults and exceptions"}));
    }

    public static class Financial extends CatalaStruct {
        
        final CatalaInteger decision;
        
        Financial
            (final CatalaBool pknown_in, final CatalaInteger pvalue_in,
             final CatalaBool aknown_in, final CatalaInteger avalue_in) {
            final CatalaBool pknown = pknown_in;
            final CatalaInteger pvalue = pvalue_in;
            final CatalaBool aknown = aknown_in;
            final CatalaInteger avalue = avalue_in;
            final CatalaInteger decision;
            if (pknown.and
                 (pvalue.greaterEqThan(new CatalaInteger("4000000000"))).or
                 (aknown.and
                   (avalue.greaterEqThan(new CatalaInteger("8000000000")))).asBoolean()) {
                decision = new CatalaInteger("1");
            } else if (pknown.and(aknown).asBoolean()) {
                decision = new CatalaInteger("0");
            } else {
                decision = new CatalaInteger("-1");
            }
            this.decision = decision;
        }
        
        static class FinancialOut extends CatalaStruct {
            final CatalaInteger decision;
            FinancialOut (final CatalaInteger decision) {
                this.decision = decision;
            }
        }
        
        Financial (FinancialOut result) {
            this.decision = result.decision;
        }
    }

    public static class Exceptions extends CatalaStruct {
        
        final CatalaInteger decision;
        final CatalaInteger amount;
        
        Exceptions
            (final CatalaBool xknown_in, final CatalaBool xvalue_in,
             final CatalaBool yknown_in, final CatalaBool yvalue_in) {
            final CatalaBool xknown = xknown_in;
            final CatalaBool xvalue = xvalue_in;
            final CatalaBool yknown = yknown_in;
            final CatalaBool yvalue = yvalue_in;
            final CatalaInteger decision;
            if (xknown.and(xvalue.and(yknown.and(yvalue))).asBoolean()) {
                decision = new CatalaInteger("2");
            } else if (xknown.and(yknown).asBoolean()) {
                decision = new CatalaInteger("3");
            } else {
                decision = new CatalaInteger("-1");
            }
            final CatalaInteger amount;
            if (yknown.and(yvalue).asBoolean()) {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("10"),
                       Globals.loc.get(2))).get(0));
            } else if (xknown.and(xvalue).asBoolean()) {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("10"),
                       Globals.loc.get(1))).get(0));
            } else {
                amount = CatalaValue.<CatalaInteger>cast
                   ((new CatalaTuple
                      (new CatalaInteger("0"),
                       Globals.loc.get(0))).get(0));
            }
            this.decision = decision;
            this.amount = amount;
        }
        
        static class ExceptionsOut extends CatalaStruct {
            final CatalaInteger decision;
            final CatalaInteger amount;
            ExceptionsOut (final CatalaInteger decision,
                           final CatalaInteger amount) {
                this.decision = decision;
                this.amount = amount;
            }
        }
        
        Exceptions (ExceptionsOut result) {
            this.decision = result.decision;
            this.amount = result.amount;
        }
    }
    
}
