package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaBool result;
        
        Control (final CatalaDate a_in, final CatalaDate b_in) {
            final CatalaDate a = a_in;
            final CatalaDate b = b_in;
            final CatalaBool result = a.greaterThan(b);
            this.result = result;
            NativeBridge.capture(this, "result", this.result);
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaBool result;
            ControlOut (final CatalaBool result) {
                this.result = result;
            NativeBridge.capture(this, "result", this.result);
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
        
        public static Control apply(final CatalaDate a_in,
                                    final CatalaDate b_in) {
            return new Control(a_in, b_in);
        }
    }
    
}
