package hk.legalmath;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

/** Generated RuleIR 0.1 policy. Authority is supplied by an external release record. */
public final class Policy_21c2aa1daaa897bf7d7c {
    private Policy_21c2aa1daaa897bf7d7c() {}
    public static final String BUNDLE_HASH = "21c2aa1daaa897bf7d7cf23ebe3f81ee8e8447bc6cd08a1b0936071bc4109fb9";
    private static final Policy POLICY = new Policy(new String(Base64.getDecoder().decode(String.join("", new String[]{
"eyJidW5kbGVfaWQiOiJzZWFyY2guNGI1OTMzM2NjZGNiMjVkNmI2ODQiLCJmYWN0cyI6W3siZGVzY3JpcHRpb24iOiJTZXJ2aWNlcyBjb25zdGl0dXRlIHJlZ3VsYXRlZCBhY3Rpdml0eSBhZnRlciBhcHBsaWNhYmxlIGNhcnZlLW91dHM7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJyZWd1bGF0ZWQiLCJ0eXBlIjoiYm9vbCJ9LHsiZGVzY3JpcHRpb24iOiJQcm92aXNpb24gb2YgdGhlIHNlcnZpY2VzIGNvbnN0aXR1dGVzIGNhcnJ5aW5nIG9uIGEgYnVzaW5lc3M7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJidXNpbmVzcyIsInR5cGUiOiJib29sIn0seyJkZXNjcmlwdGlvbiI6IlRoYXQgYnVzaW5lc3MgaXMgY2FycmllZCBvbiBpbiBIb25nIEtvbmc7IHVuaXRzOiB0cnV0aCB2YWx1ZSIsIm5hbWUiOiJob25nX2tvbmciLCJ0eXBlIjoiYm9vbCJ9XSwiaW50ZXJwcmV0YXRpb25zIjpbeyJiYXNpcyI6InJldmlld2VyX2ludGVycHJldGF0aW9uIiwiaWQiOiJyZWFkaW5nIiwiaXNzdWVfaWRzIjpbXSwic291cmNlX3NwYW5faWRzIjpbInMuZGFhMTg3NjMxNjY0MS51MzguMjc2ODEiXSwic3RhdGVtZW50IjoiVW5yZXZpZXdlZCBpbnRlcnByZXRhdGlvbjogW1RSVUVfSVNfU0FUSVNGSUVEXSBUcnVlIG1lYW5zIHRoYXQgYXQgbGVhc3Qgb25lIHN1cHBsaWVkIGZhY3RvciBpcyBzYXRpc2ZpZWQgYW5kLCB1bmRlciB0aGUgZXhwbGljaXQgY29tcGxldGVuZXNzIGFzc3VtcHRpb24sIHRoZSBzZWxlY3RlZCBsaWNlbnNpbmctdHJpZ2dlciBhbnRlY2VkZW50IGlzIHNhdGlzZmllZC4gVHdvIG9yIHRocmVlIHNhdGlzZmllZCBmYWN0b3JzIGFsc28geWllbGQgdHJ1ZS4gVGhpcyBpcyBhIGNvbmRpdGlvbmFsIGludGVycHJldGF0aW9uLCBub3QgYSBzb3VyY2UtZXN0YWJsaXNoZWQgZmluZGluZyBvZiBzdWZmaWNpZW5jeS4ifV0sInJ1bGVzIjpbeyJib2R5Ijp7ImFyZ3MiOlt7Im5hbWUiOiJyZWd1bGF0ZWQiLCJub2RlX2lkIjoiYm9keS4yIiwib3AiOiJmYWN0In0seyJuYW1lIjoiYnVzaW5lc3MiLCJub2RlX2lkIjoiYm9keS4zIiwib3AiOiJmYWN0In0seyJuYW1lIjoiaG9uZ19rb25nIiwibm9kZV9pZCI6ImJvZHkuNCIsIm9wIjoiZmFjdCJ9XSwibm9kZV9pZCI6ImJvZHkuMSIsIm9wIjoiYW55In0sImlkIjoic2VsZWN0ZWQuY29udHJvbCIsImludGVycHJldGF0aW9uX2lkIjoicmVhZGluZyIsInNjb3BlIjp7Im5vZGVfaWQiOiJzY29wZS4xIiwib3AiOiJsaXRlcmFsIiwidHlwZSI6ImJvb2wiLCJ2YWx1ZSI6dHJ1ZX0sInNvdXJjZV9zcGFuX2lkcyI6WyJzLmRhYTE4NzYzMTY2NDEudTM4LjI3NjgxIl0sInR5cGUiOiJib29sIn1dLCJzb3VyY2Vfc3BhbnMiOlt7ImVuZCI6MjgxNzYsImlkIjoicy5kYWExODc2MzE2NjQxLnUzOC4yNzY4MSIsInBhZ2UiOjEsInF1b3RlX3NoYTI1NiI6ImVlZGJkNWVlMDlkYWIzMTUzZTNkMDczMjc3MTY2Zjc0MmMzYWIzMjMxMTZjNGVkYzRmYmZkZjk3M2I0MDcxNzkiLCJyYXdfc2hhMjU2IjoiNDQyNjM4MThiNzZlZTBjMmFmNDAwMzI4YzE5OThjMTAxMDdhOTYyYzI4ODQzZDExODZlZmUwOGNkNTRjMWE4YSIsInNvdXJjZV9pZCI6ImRhYTE4NzYzMTY2NDEiLCJzdGFydCI6Mjc2ODEsInRleHRfc2hhMjU2IjoiZWM1MWE3NDMwMDNjY2Q3NzVmYWRiZTZmMDVjYWFlMzFlZTE4NjhjM2RmOWNmZDJhZTMzNTc0NjFiMDhkOTQzNSJ9XSwic3BlY192ZXJzaW9uIjoiMC4xIiwidmFsaWRfZnJvbSI6IjIwMjYtMDktMjRUMDQ6MjA6MDAuMDAwMDAwWiIsInZhbGlkX3VudGlsIjpudWxsfQ=="
    })), StandardCharsets.UTF_8));
    public static String evaluate(String snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
    public static Map<String,Object> evaluate(Map<String,Object> snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
}
