package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaMoney result;
        
        Control (final CatalaMoney amount_in) {
            final CatalaMoney amount = amount_in;
            final CatalaMoney
                result = amount.multiply
                          (new CatalaDecimal(new CatalaInteger("1"), new CatalaInteger("2")));
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaMoney result;
            ControlOut (final CatalaMoney result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
