CREATE TABLE records(hash TEXT PRIMARY KEY, kind TEXT NOT NULL, blob_hash TEXT NOT NULL);
CREATE INDEX records_kind ON records(kind);
CREATE TABLE identities(id TEXT PRIMARY KEY, roles TEXT NOT NULL, token_hash TEXT UNIQUE NOT NULL);
CREATE TABLE bundles(hash TEXT PRIMARY KEY REFERENCES records(hash), author TEXT NOT NULL REFERENCES identities(id), parent_hash TEXT REFERENCES bundles(hash), state TEXT NOT NULL CHECK(state IN ('DRAFT','IN_REVIEW','APPROVED','RELEASED','RETIRED')), revision INTEGER NOT NULL);
CREATE TABLE reviews(bundle_hash TEXT NOT NULL REFERENCES bundles(hash), reviewer TEXT NOT NULL REFERENCES identities(id), role TEXT NOT NULL, record_hash TEXT NOT NULL REFERENCES records(hash), PRIMARY KEY(bundle_hash,role));
CREATE TABLE issues(id TEXT NOT NULL, bundle_hash TEXT NOT NULL REFERENCES bundles(hash), payload_hash TEXT NOT NULL REFERENCES records(hash), resolved INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(bundle_hash,id));
CREATE TABLE sources(revision_id TEXT PRIMARY KEY, source_id TEXT NOT NULL, payload_hash TEXT NOT NULL REFERENCES records(hash));
CREATE INDEX source_identity ON sources(source_id);
CREATE TABLE derivatives(hash TEXT PRIMARY KEY REFERENCES records(hash), revision_id TEXT NOT NULL REFERENCES sources(revision_id));
CREATE TABLE dependencies(id TEXT PRIMARY KEY, from_revision_id TEXT NOT NULL REFERENCES sources(revision_id), target_revision_id TEXT REFERENCES sources(revision_id), payload_hash TEXT NOT NULL REFERENCES records(hash), resolved INTEGER NOT NULL);
CREATE TABLE coverage(bundle_hash TEXT NOT NULL REFERENCES bundles(hash), span_id TEXT NOT NULL, payload_hash TEXT NOT NULL REFERENCES records(hash), PRIMARY KEY(bundle_hash,span_id));
CREATE TABLE facts(record_id TEXT PRIMARY KEY, subject_id TEXT NOT NULL, fact_name TEXT NOT NULL, type TEXT NOT NULL, valid_from TEXT NOT NULL, valid_until TEXT, recorded_at TEXT NOT NULL, payload_hash TEXT NOT NULL REFERENCES records(hash));
CREATE INDEX fact_selection ON facts(subject_id,fact_name,valid_from,recorded_at);
CREATE TABLE supersession(corrector TEXT NOT NULL REFERENCES facts(record_id), predecessor TEXT NOT NULL REFERENCES facts(record_id), PRIMARY KEY(corrector,predecessor));
CREATE TABLE applicability(hash TEXT PRIMARY KEY REFERENCES records(hash), bundle_hash TEXT NOT NULL REFERENCES bundles(hash), scope_key TEXT NOT NULL, reviewer TEXT NOT NULL REFERENCES identities(id));
CREATE TABLE builds(hash TEXT PRIMARY KEY REFERENCES records(hash), bundle_hash TEXT NOT NULL REFERENCES bundles(hash), jar_hash TEXT NOT NULL);
CREATE TABLE verifications(hash TEXT PRIMARY KEY REFERENCES records(hash), build_hash TEXT NOT NULL REFERENCES builds(hash), bundle_hash TEXT NOT NULL REFERENCES bundles(hash), passed INTEGER NOT NULL);
CREATE TABLE release_manifests(hash TEXT PRIMARY KEY REFERENCES records(hash), build_hash TEXT NOT NULL REFERENCES builds(hash), verification_hash TEXT NOT NULL REFERENCES verifications(hash), applicability_hash TEXT NOT NULL REFERENCES applicability(hash));
CREATE TABLE releases(hash TEXT PRIMARY KEY REFERENCES records(hash), bundle_hash TEXT NOT NULL REFERENCES bundles(hash), manifest_hash TEXT NOT NULL REFERENCES release_manifests(hash), scope_key TEXT NOT NULL, valid_from TEXT NOT NULL, valid_until TEXT, activated_at TEXT NOT NULL, retired_at TEXT);
CREATE INDEX release_selection ON releases(scope_key,valid_from,valid_until,retired_at);
CREATE TABLE evaluations(result_hash TEXT PRIMARY KEY, payload_hash TEXT NOT NULL REFERENCES records(hash), bundle_hash TEXT NOT NULL REFERENCES bundles(hash), release_hash TEXT REFERENCES releases(hash));
CREATE TABLE streams(id TEXT PRIMARY KEY, header_hash TEXT NOT NULL REFERENCES records(hash), revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE events(id TEXT PRIMARY KEY, stream_id TEXT NOT NULL REFERENCES streams(id), sequence INTEGER NOT NULL CHECK(sequence>0), payload_hash TEXT NOT NULL REFERENCES records(hash), UNIQUE(stream_id,sequence));
CREATE TABLE replays(hash TEXT PRIMARY KEY REFERENCES records(hash), stream_id TEXT NOT NULL REFERENCES streams(id));
CREATE TABLE jobs(id TEXT PRIMARY KEY, kind TEXT NOT NULL, request_hash TEXT NOT NULL REFERENCES records(hash), state TEXT NOT NULL CHECK(state IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED')), result_hash TEXT REFERENCES records(hash), diagnostic TEXT, revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE idempotency(caller TEXT NOT NULL, key TEXT NOT NULL, request_hash TEXT NOT NULL, response_hash TEXT NOT NULL REFERENCES records(hash), PRIMARY KEY(caller,key));
CREATE TABLE audit(sequence INTEGER PRIMARY KEY, previous_hash TEXT, hash TEXT UNIQUE NOT NULL, payload_hash TEXT NOT NULL REFERENCES records(hash));
