package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Lowered {

    public static class Globals {

        public static final CatalaArray<CatalaPosition> loc =
            new CatalaArray<CatalaPosition>
             (new CatalaPosition
               ("Lowered.catala_en", 39, 12, 39, 21,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 40, 12, 40, 22,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 224, 44, 233,
                new String[]{"Generated RuleIR calculations"}),
              new CatalaPosition
               ("Lowered.catala_en", 44, 237, 44, 247,
                new String[]{"Generated RuleIR calculations"}));
    }

    public static class Operand extends CatalaStruct {
        
        public final CatalaInteger slot;
        public final CatalaInteger code;
        public final CatalaInteger payload;
        
        public Operand (final CatalaInteger slot, final CatalaInteger code,
                        final CatalaInteger payload) {
            this.slot = slot;
            this.code = code;
            this.payload = payload;
        }
    }

    public static class N0 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N0 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N0Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N0Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N0 (N0Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N4 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N4 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("2")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("2");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N4Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N4Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N4 (N4Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N5 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N5 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger selected = new CatalaInteger("-1");
            final CatalaOption<CatalaTuple> leftValue;
            final CatalaInteger leftValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                leftValue1 = tup_arg_109 -> {
                    CatalaInteger sum1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_109.get(0));
                    CatalaInteger sum2 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_109.get(1));
                    return sum1.add(sum2); };
            final CatalaFunction<Operand,CatalaInteger>
                leftValue1__1 = x -> {
                    if (x.slot.equalsTo(new CatalaInteger("0")).asBoolean()) {
                        return x.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> leftValue1__2 =
                operands.map(leftValue1__1).reduce(leftValue1);
            if (leftValue1__2.isNone()) {
                leftValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__1 = leftValue1__2.get();
                leftValue__1 = x__1;
            }
            leftValue = CatalaOption.some
                         (new CatalaTuple(leftValue__1, Globals.loc.get(0)));
            final CatalaOption<CatalaTuple> rightValue;
            final CatalaInteger rightValue__1;
            final CatalaFunction<CatalaTuple,CatalaInteger>
                rightValue1 = tup_arg_110 -> {
                    CatalaInteger sum1__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_110.get(0));
                    CatalaInteger sum2__1 = CatalaValue.<CatalaInteger>cast
                       (tup_arg_110.get(1));
                    return sum1__1.add(sum2__1); };
            final CatalaFunction<Operand,CatalaInteger>
                rightValue1__1 = x__1 -> {
                    if (x__1.slot.equalsTo(new CatalaInteger("1")).asBoolean()) {
                        return x__1.payload;
                    } else {
                        return new CatalaInteger("0");
                    } };
            CatalaOption<CatalaInteger> rightValue1__2 =
                operands.map(rightValue1__1).reduce(rightValue1);
            if (rightValue1__2.isNone()) {
                rightValue__1 = new CatalaInteger("0");
            } else {
                CatalaInteger x__2 = rightValue1__2.get();
                rightValue__1 = x__2;
            }
            rightValue = CatalaOption.some
                          (new CatalaTuple(rightValue__1, Globals.loc.get(1)));
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x__2 -> {
                    return x__2.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__3 -> {
                        return x__3.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__4 -> {
                            return x__4.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaInteger resultStatus__4;
                        if (leftValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(2));
                        } else {
                            CatalaTuple arg = leftValue.get();
                            resultStatus__4 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        final CatalaInteger resultStatus__5;
                        if (rightValue.isNone()) {
                            throw CatalaError.error(CatalaError.Error.NoValue, Globals.loc.get(3));
                        } else {
                            CatalaTuple arg = rightValue.get();
                            resultStatus__5 = CatalaValue.<CatalaInteger>cast
                               (arg.get(0));
                        }
                        if (resultStatus__4.greaterEqThan(resultStatus__5).asBoolean()) {
                            resultStatus = new CatalaInteger("1");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N5Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N5Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N5 (N5Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N7 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N7 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus = new CatalaInteger("3");
            final CatalaInteger resultValue = new CatalaInteger("20420");
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N7Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N7Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N7 (N7Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N9 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N9 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N9Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N9Out (final CatalaInteger resultStatus,
                   final CatalaInteger resultValue,
                   final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N9 (N9Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N10 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N10 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("1")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("1");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("0")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("0");
                        } else {
                            resultStatus = new CatalaInteger("2");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N10Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N10Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N10 (N10Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }

    public static class N14 extends CatalaStruct {
        
        final CatalaInteger resultStatus;
        final CatalaInteger resultValue;
        final CatalaInteger selected;
        
        N14 (final CatalaArray<Operand> operands_in) {
            final CatalaArray<Operand> operands = operands_in;
            final CatalaInteger resultStatus;
            final CatalaFunction<Operand,CatalaBool>
                resultStatus__1 = x -> {
                    return x.code.equalsTo(new CatalaInteger("5")); };
            if (CatalaBool.of(operands.find(resultStatus__1).isSome()).asBoolean()) {
                resultStatus = new CatalaInteger("5");
            } else {
                final CatalaFunction<Operand,CatalaBool>
                    resultStatus__2 = x__1 -> {
                        return x__1.code.equalsTo(new CatalaInteger("4")); };
                if (CatalaBool.of(operands.find(resultStatus__2).isSome()).asBoolean()) {
                    resultStatus = new CatalaInteger("4");
                } else {
                    final CatalaFunction<Operand,CatalaBool>
                        resultStatus__3 = x__2 -> {
                            return x__2.code.equalsTo(new CatalaInteger("0")); };
                    if (CatalaBool.of(operands.find(resultStatus__3).isSome()).asBoolean()) {
                        resultStatus = new CatalaInteger("0");
                    } else {
                        final CatalaFunction<Operand,CatalaBool>
                            resultStatus__4 = x__3 -> {
                                return x__3.code.equalsTo
                                        (new CatalaInteger("1")); };
                        if (CatalaBool.of(operands.find(resultStatus__4).isSome()).asBoolean()) {
                            resultStatus = new CatalaInteger("2");
                        } else {
                            resultStatus = new CatalaInteger("1");
                        }
                    }
                }
            }
            final CatalaInteger resultValue;
            if (resultStatus.equalsTo(new CatalaInteger("1")).asBoolean()) {
                resultValue = new CatalaInteger("1");
            } else {
                resultValue = new CatalaInteger("0");
            }
            final CatalaInteger selected = new CatalaInteger("-1");
            this.resultStatus = resultStatus;
            this.resultValue = resultValue;
            this.selected = selected;
        }
        
        static class N14Out extends CatalaStruct {
            final CatalaInteger resultStatus;
            final CatalaInteger resultValue;
            final CatalaInteger selected;
            N14Out (final CatalaInteger resultStatus,
                    final CatalaInteger resultValue,
                    final CatalaInteger selected) {
                this.resultStatus = resultStatus;
                this.resultValue = resultValue;
                this.selected = selected;
            }
        }
        
        N14 (N14Out result) {
            this.resultStatus = result.resultStatus;
            this.resultValue = result.resultValue;
            this.selected = result.selected;
        }
    }
    
}
