package hk.legalmath;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Map;

/** Generated RuleIR 0.1 policy. Authority is supplied by an external release record. */
public final class Policy_492fbaab230d50033fc7 {
    private Policy_492fbaab230d50033fc7() {}
    public static final String BUNDLE_HASH = "492fbaab230d50033fc746ea7d57feb92ac2d22972e4b9a3696f1ce7a441a970";
    private static final Policy POLICY = new Policy(new String(Base64.getDecoder().decode(String.join("", new String[]{
"eyJidW5kbGVfaWQiOiJzZWFyY2guNDI0NGNmZjc2OTEwYmMwYmQyZDciLCJmYWN0cyI6W3siZGVzY3JpcHRpb24iOiJhOyB1bml0czogZGltZW5zaW9ubGVzcyIsIm5hbWUiOiJhIiwidHlwZSI6ImRhdGUifSx7ImRlc2NyaXB0aW9uIjoiYjsgdW5pdHM6IGRpbWVuc2lvbmxlc3MiLCJuYW1lIjoiYiIsInR5cGUiOiJkYXRlIn1dLCJpbnRlcnByZXRhdGlvbnMiOlt7ImJhc2lzIjoic3ludGhldGljX3Rlc3QiLCJpZCI6InJlYWRpbmciLCJpc3N1ZV9pZHMiOltdLCJzb3VyY2Vfc3Bhbl9pZHMiOlsicy5jbGF1c2Uub25lIl0sInN0YXRlbWVudCI6IlVucmV2aWV3ZWQgaW50ZXJwcmV0YXRpb246IENvbXB1dGUgdGhlIGRlY2xhcmVkIG91dHB1dHMgZm9yIHRoZSBzdXBwbGllZCBwcmltaXRpdmUgaW5wdXRzLiJ9XSwicnVsZXMiOlt7ImJvZHkiOnsiY21wIjoiZ3QiLCJsZWZ0Ijp7Im5hbWUiOiJhIiwibm9kZV9pZCI6ImJvZHkuMiIsIm9wIjoiZmFjdCJ9LCJub2RlX2lkIjoiYm9keS4xIiwib3AiOiJjb21wYXJlIiwicmlnaHQiOnsibmFtZSI6ImIiLCJub2RlX2lkIjoiYm9keS4zIiwib3AiOiJmYWN0In19LCJpZCI6InNlbGVjdGVkLmNvbnRyb2wiLCJpbnRlcnByZXRhdGlvbl9pZCI6InJlYWRpbmciLCJzY29wZSI6eyJub2RlX2lkIjoic2NvcGUuMSIsIm9wIjoibGl0ZXJhbCIsInR5cGUiOiJib29sIiwidmFsdWUiOnRydWV9LCJzb3VyY2Vfc3Bhbl9pZHMiOlsicy5jbGF1c2Uub25lIl0sInR5cGUiOiJib29sIn1dLCJzb3VyY2Vfc3BhbnMiOlt7ImVuZCI6MTY4LCJpZCI6InMuY2xhdXNlLm9uZSIsInBhZ2UiOjEsInF1b3RlX3NoYTI1NiI6IjhmZTUwYTcyYjA1NGJmZWFjMTBlZGQyYjQxN2JjMTM0MTJkZTUxZWUyMDYyOThhOWVjYzk1YjRjZThhMDBiYzciLCJyYXdfc2hhMjU2IjoiOGZlNTBhNzJiMDU0YmZlYWMxMGVkZDJiNDE3YmMxMzQxMmRlNTFlZTIwNjI5OGE5ZWNjOTViNGNlOGEwMGJjNyIsInNvdXJjZV9pZCI6InN5bnRoZXRpYy5zeW50aGV0aWMubmF0aXZlLnNlbWFudGljcy5kYXRlIiwic3RhcnQiOjAsInRleHRfc2hhMjU2IjoiOGZlNTBhNzJiMDU0YmZlYWMxMGVkZDJiNDE3YmMxMzQxMmRlNTFlZTIwNjI5OGE5ZWNjOTViNGNlOGEwMGJjNyJ9XSwic3BlY192ZXJzaW9uIjoiMC4xIiwidmFsaWRfZnJvbSI6IjIwMjAtMDEtMDFUMDA6MDA6MDAuMDAwMDAwWiIsInZhbGlkX3VudGlsIjpudWxsfQ=="
    })), StandardCharsets.UTF_8));
    public static String evaluate(String snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
    public static Map<String,Object> evaluate(Map<String,Object> snapshot, String ruleId, String validAt, String knownAt, String mode) {
        return POLICY.evaluate(snapshot, ruleId, validAt, knownAt, mode);
    }
}
