package catala.stdlib;

/* This file has been generated by the Catala compiler, do not edit! */

import catala.runtime.*;
import catala.runtime.exception.*;
import catala.stdlib.*;

public class Native {

    public static class Control extends CatalaStruct {
        
        final CatalaBool result;
        
        Control
            (final CatalaBool gift_in, final CatalaBool discount_in,
             final CatalaBool specific_in, final CatalaBool producttype_in) {
            final CatalaBool gift = gift_in;
            final CatalaBool discount = discount_in;
            final CatalaBool specific = specific_in;
            final CatalaBool producttype = producttype_in;
            final CatalaBool
                result = gift.and
                          (discount.not().and(specific.or(producttype)));
            this.result = result;
        }
        
        static class ControlOut extends CatalaStruct {
            final CatalaBool result;
            ControlOut (final CatalaBool result) {
                this.result = result;
            }
        }
        
        Control (ControlOut result) {
            this.result = result.result;
        }
    }
    
}
